### ISSUE TITLE
MOT0109_0: Spatial: Failed to open device: Timed Out

### ISSUE THREAD

**Issue by DoneMan** [ros-drivers/phidgets_drivers#105]
did anyone encounter this before?
on branch noetic.
i have the phidgets spatial 3/3/3 MOT0109_0, i'm trying to launch the spatial.launch and i get these errors:

[ INFO] [1634714179.485430556]: Loading nodelet /PhidgetsSpatialNodelet of type phidgets_spatial/PhidgetsSpatialNodelet to manager imu_manager with the following remappings:
[ INFO] [1634714179.487040471]: waitForService: Service [/imu_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1634714179.492581832]: Loading nodelet /ImuFilterNodelet of type imu_filter_madgwick/ImuFilterNodelet to manager imu_manager with the following remappings:
[ INFO] [1634714179.494079519]: waitForService: Service [/imu_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [1634714179.504203262]: Initializing nodelet with 8 worker threads.
[ INFO] [1634714179.508148068]: waitForService: Service [/imu_manager/load_nodelet] is now available.
[ INFO] [1634714179.510623053]: Initializing Phidgets SPATIAL Nodelet
[ INFO] [1634714179.510687100]: Starting Phidgets SPATIAL
[ INFO] [1634714179.510703508]: Opening spatial
[ INFO] [1634714179.513058698]: Connecting to Phidgets Spatial serial 373265, hub port 0 ...
[ INFO] [1634714179.515118447]: waitForService: Service [/imu_manager/load_nodelet] is now available.
[ERROR] [1634714180.514098019]: Spatial: Failed to open device: Timed Out
[FATAL] [1634714180.515002304]: Failed to load nodelet '/PhidgetsSpatialNodelet` of type `phidgets_spatial/PhidgetsSpatialNodelet` to manager `imu_manager'
[ INFO] [1634714180.525610450]: Initializing IMU Filter Nodelet
[ INFO] [1634714180.528075648]: Starting ImuFilter
[ INFO] [1634714180.539780216]: Using dt computed from message headers
[ INFO] [1634714180.539883555]: The gravity vector is kept in the IMU message.
[ INFO] [1634714180.560925486]: Imu filter gain set to 0.100000
[ INFO] [1634714180.560996819]: Gyro drift bias set to 0.000000
[ INFO] [1634714180.561031830]: Magnetometer bias values: 0.000000 0.000000 0.000000
[PhidgetsSpatialNodelet-3] process has died [pid 6039, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load phidgets_spatial/PhidgetsSpatialNodelet imu_manager __name:=PhidgetsSpatialNodelet __log:=/home/user/.ros/log/9edd08f0-3175-11ec-92fd-b05cdaa8ff51/PhidgetsSpatialNodelet-3.log].
log file: /home/user/.ros/log/9edd08f0-3175-11ec-92fd-b05cdaa8ff51/PhidgetsSpatialNodelet-3*.log
[ WARN] [1634714190.572501364]: Still waiting for data on topics /imu/data_raw and /imu/mag...

can anyone help please?

**Comment by mintar** [comment]
This is the crucial line:

>  [ERROR] [1634714180.514098019]: Spatial: Failed to open device: Timed Out

So it seems like the driver tried to open the USB device, but failed.

The [phidgets webpage](https://www.phidgets.com/docs/General_Troubleshooting) says:

> Make sure you're setting all of the matching parameters correctly. You can learn more by reading our page on Addressing Phidgets. Also make sure that the channels you're trying to open aren't already opened in another program (including the Phidget Control Panel). 

Some more things to check:

* Did you set up the udev rules properly? (see README)
* Does the device show up in `lsusb`?

**Comment by DoneMan** [comment]
@mintar 
yes, i have set up the udev-rules as was instructed in the wiki
yes when typing lsusb the device shows up as follows:
Bus 001 Device 042: ID 06c2:008c Phidgets Inc. (formerly GLAB)

**Comment by DoneMan** [comment]
@mintar any ideas on what can cause this?

**Comment by phidgets** [comment]
MOT0109_0 requires phidget22. The module will need to be migrated from phidget21 to phidget22.

**Comment by DoneMan** [comment]
@phidgets branch noetic uses phidget22

**Comment by phidgets** [comment]
Ok, i didn’t have a look at the other branch. It looks to be pulling in a particular version of libphidget22 from 1.5 years ago. MOT0109 is a brand new device and requires version 1.7.20210816 or newer of the library.

**Comment by DoneMan** [comment]
@phidgets i see. looks like i will have to edit the source code for it to take the new package.
thank you very much for your support.
also 
@mintar  thank you very much.

**Comment by DoneMan** [comment]
@mintar how complicated do you think this is to be done? updating the libphidgets22 library?

**Comment by mintar** [comment]
@phidgets : Thanks for the hint!

@DoneMan : I've just pushed the required changes to the `libphidgets22-1.7-noetic` branch. Please test whether it's working and leave a comment!

**Comment by DoneMan** [comment]
@mintar great! i am checking now

**Comment by DoneMan** [comment]
@mintar it works!!!  you are a freaking king! thank you very much!!

**Comment by Hobbani** [comment]
I face the same issue with ros2 foxy. Whatever I try I still get the following:
ros2 launch phidgets_spatial spatial-launch.py
[INFO] [launch]: All log files can be found below /home/horizon/.ros/log/2025-10-10-17-59-59-991439-iocore-4346
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [component_container-1]: process started with pid [4368]
[component_container-1] [INFO] [1760112000.691364815] [phidget_container]: Load Library: /home/horizon/ros2_ws/install/phidgets_spatial/lib/libphidgets_spatial.so
[component_container-1] [INFO] [1760112000.709721337] [phidget_container]: Found class: rclcpp_components::NodeFactoryTemplate<phidgets::SpatialRosI>
[component_container-1] [INFO] [1760112000.709864965] [phidget_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<phidgets::SpatialRosI>
[component_container-1] [INFO] [1760112000.720859875] [phidgets_spatial]: Starting Phidgets Spatial
[component_container-1] [INFO] [1760112000.722263176] [phidgets_spatial]: Connecting to Phidgets Spatial serial -1, hub port 0 ...
[component_container-1] [ERROR] [1760112001.765944949] [phidgets_spatial]: Spatial: Failed to open device: Timed Out
[component_container-1] [ERROR] [1760112001.777919331] [phidget_container]: Component constructor threw an exception: Failed to open device: Timed Out
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'phidgets_spatial' of type 'phidgets::SpatialRosI' in container '/phidget_container': Component constructor threw an exception: Failed to open device: Timed Out
